### ISSUE TITLE
Cannot launch safe_teleop_stage.launch

### ISSUE THREAD

**Issue by 7675t** [SharedAutonomyToolkit/shared_autonomy_manipulation#10]
I tried this package as:
```
$ roslaunch safe_teleop_stage safe_teleop_stage.launch
```
got
```
ResourceNotFound: bosch_worlds
```
And other packages in the launch file such as segway_joystick ans segway_config don't exist.

My environment is ROS Indigo, and using master branch.

**Comment by k-okada** [comment]
@7675t  please look at #12
 should I add rviz example?

**Comment by 7675t** [comment]
Thanks, I confirmed the stage works. 
And yes, it would be helpful if rviz config is available.
Now I'm using kinetic and hydro-devel branch.

**Comment by k-okada** [comment]
Ok, I have added rviz config and integration of move_base + safe_teleop. Please look at my commit message to how to select move_base output and safe_teleop. This is very useful, not only you can control robot by joystick, but also holding a button to pause the robot while it is navigating.

https://github.com/SharedAutonomyToolkit/shared_autonomy_manipulation/pull/12/commits/1888e4b7daed7e676e5efa77a73a451dc35de8f6

Since I do not have joystick in my home, i used keyboard_teleop and have to use manually `rosservice call` to switch the command, but if you have joystick, you can map the button and rosservice very easiry
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml#L21-L24

If you haven't try `move_base` + `safe_teleop`, please try with your roomba robot.

**Comment by k-okada** [comment]
I'm not sure if we should depend on 'real' joystick to this example, at least I do not have them right now. Other possibility is ;
- http://wiki.ros.org/keyboardteleopjs (used in https://github.com/tork-a/hakuto/blob/master/tetris_launch/www/joystick.html )
- android app https://qiita.com/kazuyamashi/items/0e813d0e31182e7c6b53 

But, we still need to add button feature to them.
